<a href="https://colab.research.google.com/github/fnweb3/numpy_study/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy, Libreria para ciencia de datos


In [ ]:
import numpy as np


In [ ]:
array_1d=np.array([1,4,3])
array_1d


array([1, 4, 3])

In [ ]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [ ]:
array_3d=np.array([[(1,4,2),(1,5,9)],[(7,5,9),(8,1,3)],[(3,5,3),(7,2,9)]], dtype=float)
array_3d


array([[[1., 4., 2.],
        [1., 5., 9.]],

       [[7., 5., 9.],
        [8., 1., 3.]],

       [[3., 5., 3.],
        [7., 2., 9.]]])

In [ ]:
print(array_3d)

[[[1. 4. 2.]
  [1. 5. 9.]]

 [[7. 5. 9.]
  [8. 1. 3.]]

 [[3. 5. 3.]
  [7. 2. 9.]]]


Creando Arrays

In [ ]:
#De ceros con 3 filas y 4 columnas
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#De unos con 2 dimensiones 4 filas 5 columnas
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
#Intervalos y saltos
np.arange(12,31,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
#Intervalo y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [ ]:
#Valor d(ado
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#Matriz identidad, diagonal de unos 
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Valores aleatorios entre 0 y 1
np.random.random((4,4))

array([[0.23460139, 0.19069966, 0.17369753, 0.02354086],
       [0.11666424, 0.06449318, 0.77111258, 0.91289689],
       [0.48405896, 0.53283877, 0.72028756, 0.41761177],
       [0.4974696 , 0.44589315, 0.85564253, 0.93799981]])

In [ ]:
#Vacio de 4 filas y 3 columnas
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#Grabar y cargar

In [39]:
#Grabar
np.save('mi_array', np.random.random((3,3)))

In [40]:
#Cargar
mi_array=np.load('mi_array.npy')
mi_array

array([[0.64017502, 0.77353132, 0.72675903],
       [0.0775844 , 0.8465942 , 0.86343744],
       [0.69877465, 0.12027638, 0.43357518]])