<a href="https://colab.research.google.com/github/fnweb3/numpy_study/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy, Libreria para ciencia de datos


In [ ]:
import numpy as np


In [ ]:
array_1d=np.array([1,4,3])
array_1d


[1 4 3]


In [ ]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [ ]:
array_3d=np.array([[(1,4,2),(1,5,9)],[(7,5,9),(8,1,3)],[(3,5,3),(7,2,9)]], dtype=float)
array_3d


array([[[1., 4., 2.],
        [1., 5., 9.]],

       [[7., 5., 9.],
        [8., 1., 3.]],

       [[3., 5., 3.],
        [7., 2., 9.]]])

In [ ]:
print(array_3d)

[[[1. 4. 2.]
  [1. 5. 9.]]

 [[7. 5. 9.]
  [8. 1. 3.]]

 [[3. 5. 3.]
  [7. 2. 9.]]]


Creando Arrays

In [ ]:
#De ceros con 3 filas y 4 columnas
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
