<a href="https://colab.research.google.com/github/fnweb3/numpy_study/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy, Libreria para ciencia de datos


In [ ]:
import numpy as np


In [ ]:
array_1d=np.array([1,4,3])
array_1d


[1 4 3]


In [ ]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [ ]:
array_3d=np.array([[(1,4,2),(1,5,9)],[(7,5,9),(8,1,3)],[(3,5,3),(7,2,9)]], dtype=float)
array_3d


array([[[1., 4., 2.],
        [1., 5., 9.]],

       [[7., 5., 9.],
        [8., 1., 3.]],

       [[3., 5., 3.],
        [7., 2., 9.]]])

In [ ]:
print(array_3d)

[[[1. 4. 2.]
  [1. 5. 9.]]

 [[7. 5. 9.]
  [8. 1. 3.]]

 [[3. 5. 3.]
  [7. 2. 9.]]]


Creando Arrays

In [ ]:
#De ceros con 3 filas y 4 columnas
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
#De unos con 2 dimensiones 4 filas 5 columnas
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [12]:
#Intervalos y saltos
np.arange(12,31,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [13]:
#Intervalo y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [14]:
#Valor d(ado
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [15]:
#Matriz identidad, diagonal de unos 
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#Valores aleatorios entre 0 y 1
np.random.random((4,4))

array([[0.18150253, 0.32400766, 0.73239544, 0.9182598 ],
       [0.19979115, 0.51523616, 0.49482538, 0.09904135],
       [0.91020964, 0.89853007, 0.82477245, 0.97674188],
       [0.86746799, 0.75115939, 0.95561287, 0.87115081]])

In [19]:
#Vacio de 4 filas y 3 columnas
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])